name: CI - ProductsCRUD

on:
  push:
    branches:
      - 'feat/add_ci'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017

    env:
      MongoDb__ConnectionString: mongodb://localhost:27017
      MongoDb__DatabaseName: ProductsCRUD_Test

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 📦 Restore
        run: dotnet restore

      - name: 🏗️ Build
        run: dotnet build --no-restore --configuration Release

      - name: 🧪 Test + Coverage
        run: |
          dotnet test \
            --no-build \
            --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutput=./coverage/ \
            /p:CoverletOutputFormat=cobertura

      - name: 📊 Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: 🔍 Debug coverage files
        run: |
          echo "Listing coverage files..."
          find . -name "*.cobertura.xml"

      - name: 📈 Generate coverage report
        run: |
          reportgenerator \
            -reports:**/coverage.cobertura.xml \
            -targetdir:./coverage-report \
            -reporttypes:TextSummary

      - name: 🚨 Validate coverage (>=80%)
        run: |
          COVERAGE=$(grep -Po 'Line coverage: \K[0-9.]+' coverage-report/Summary.txt)
          echo "Coverage: $COVERAGE%"

          COVERAGE_INT=${COVERAGE%.*}

          if [ "$COVERAGE_INT" -lt "80" ]; then
            echo "❌ Coverage abaixo de 80%"
            exit 1
          else
            echo "✅ Coverage OK"
          fi